### ISSUE TITLE
اختیاری بودن کلید در سینک کافکا

### ISSUE THREAD

**Issue by amirmohammadzakeri** [AhmadAfsharinejad/Orleans.StreamProcessing#3]
سلام.
در وضعیت فعلی انتخاب فیلد برای کلید کافکا اجباری است.
لطفا تغییراتی صورت پذیرد که این مورد اختیاری باشد.

دم شما گرم.

**Comment by AhmadAfsharinejad** [comment]
سلام
در نسخه‌های جدید این مشکل رفع شده است
